# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus-net-metrics
  description: "This repo contains a collection of useful metrics to be used with the prometheus-net library. Developed as part of Allegro Pay product."
  title: Allegro Prometheus metrics
  annotations:
    backstage.io/techdocs-ref: dir:.
    allegropay/entity-updated-at: '2023-11-03T08:15'
    github.com/project-slug: allegro/prometheus-net-metrics
  links: []
spec:
  type: library
  owner: aard
  lifecycle: production
  system: application-platform
