name: Publish Allegro.Prometheus.TrueRpsMetric

on:
  push:
    tags:
      - 'Allegro.Prometheus.TrueRpsMetric_*'

jobs:
  publish:
    uses: ./.github/workflows/template.yml
    with:
      projectName: Allegro.Prometheus.TrueRpsMetric
      publish: true
      tagName: ${{ github.ref_name }}
    secrets:
      nugetCertificate: ${{ secrets.NUGET_PRIVATE_KEY_P12 }}
      nugetCertificatePassword: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
      nugetApiKey: ${{ secrets.NUGET_API_KEY }}
